spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
---
spring:
  config:
    activate:
      on-profile: integration-test
  data:
    redis:
      host: localhost
      port: 6379
