# Build stage
FROM gradle:jdk17 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle :bootstrap:http:bootJar --no-daemon

# Package stage
FROM openjdk:17
COPY --from=build /home/gradle/src/bootstrap/http/build/libs/http-*.jar /app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]
