auth:
  jwt:
    issuer: ${JWT_ISSUER:weave}
    access:
      expire-seconds: ${JWT_ACCESS_EXPIRE_SECONDS:30}
      secret: ${JWT_ACCESS_SECRET:secret}
    refresh:
      expire-seconds: ${JWT_REFRESH_EXPIRE_SECONDS:120}
      secret: ${JWT_REFRESH_SECRET:secret}
    register:
      expire-seconds: ${JWT_REGISTER_EXPIRE_SECONDS:300}
      secret: ${JWT_REGISTER_SECRET:secret}
  open-id:
    providers:
      apple:
        jwks-uri: ${APPLE_JWKS_URI:https://appleid.apple.com/auth/keys}
      kakao:
        jwks-uri: ${KAKAO_JWKS_URI:https://kauth.kakao.com/.well-known/jwks.json}

meeting:
  team:
    invitation:
      url-prefix: ${INVITATION_URL_PREFIX:https://api.dev.team-weave.me/invitations?code=}
      expire-seconds: ${INVITATION_EXPIRE_SECONDS:3600}

---
spring:
  config:
    activate:
      on-profile: prod

meeting:
  team:
    invitation:
      url-prefix: ${INVITATION_URL_PREFIX:https://api.team-weave.me/invitations?code=}
      expire-seconds: ${INVITATION_EXPIRE_SECONDS:3600}
