aws-bucket:
  user-profile-image:
    bucket-name: ${AWS_S3_BUCKET_NAME:weave-server-dev-bucket}
    key-prefix: ${AWS_S3_PROFILE_IMAGE_BUCKET_KEY_PREFIX:user/profile-img/}
    presigned-url-expiration-min: 5
