spring:
  thymeleaf:
    prefix: classpath:/mail-templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false

# TODO(SES Sandbox): SES Sandbox 해제시 적용
#aws:
#  ses:
#    access-key: ${AWS_SES_ACCESS_KEY}
#    secret-key: ${AWS_SES_SECRET_KEY}
---
spring:
  config:
    activate:
      on-profile: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DEV_EMAIL_USERNAME}
    password: ${DEV_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
